export enum SearchAthleteRowColumnNames {
    ATHLETE_ID = 'athleteIdHeaderAdamsValue',
    ADAMS_ID = 'adamsId',
    AGE = 'age',
    BP_NUMBER = 'bloodPassportIdNumber',
    DATE_OF_BIRTH = 'dateOfBirth',
    PREFERRED_NAME = 'preferredName',
    FORMER_LAST_NAME = 'formerLastName',
    IF_ID = 'ifIdNumber',
    LATEST_TEST = 'latestTest',
    NADO_ID = 'naDOIdNumber',
    NAME = 'name',
    NATIONAL_FEDERATIONS = 'nationalFederations',
    NF_ID = 'nfIdNumber',
    PASSPORT_CUSTODIAN = 'passportCustodian',
    RETIRED_ATHLETE = 'retiredAthlete',
    SEX = 'sex',
    SPORT_NATIONALITY = 'sportNationality',
    SPORT_DISCIPLINES = 'sportDisciplines',
    TEAMS = 'teams',
    TESTING_POOL_TYPES = 'testingPoolTypes',
    WHEREABOUTS_CUSTODIAN = 'whereaboutsCustodianOrganization',
}
