export enum AthleteActivePage {
    ACCOUNT = 'ACCOUNT',
    ADRV = 'ADRV',
    BIOLOGICAL_PASSPORT = 'BIOLOGICAL-PASSPORT',
    DASHBOARD = 'DASHBOARD',
    PERMISSIONS = 'PERMISSIONS',
    PROFILE = 'PROFILE',
    SANCTIONS = 'SANCTIONS',
    TESTS = 'TESTS',
    TUE = 'TUE',
    WHEREABOUTS = 'WHEREABOUTS',
}
