export const ATHLETE_LEVEL_LIST = ['International', 'National', 'Other'];
export const BLOOD_PASSPORT_SPECIFIC_CODE = 'Blood_passport';
export const DEFAULT_MAX_INTERVAL = 60000;
export const DEFAULT_POLLING_INTERVAL = 30000;
export const GET_PREFERENCES_MAX_RETRIES = 5;
export const GET_PREFERENCES_RETRY_INTERVAL = 1000;
export const MAX_NON_CONFORMITIES = 9;
export const MAX_NUMBER_OF_ANALYSES_PER_SAMPLE_TYPE = 5;
export const MAX_NUMBER_OF_ROWS = 25;
export const MAX_NUMBER_OF_SAMPLES = 20; // 5 analysis per sample type * 4 sample types
export const MAX_NUMBER_OF_TESTS_WARNING = 100; // Threshold before showing a Warning that tests will cause slowness
export const MAXIMUM_LEAD_DCOS = 1;
export const MLA_OPTIONAL_LEVEL = 5;
export const PROPERTY_MAX_MO_RESULTS = 'max.mission.order.search.results';
export const USER_INACTIVITY_TIMEOUT = 60000;
