export enum AttachmentType {
    NOTIFICATION = 'NOTIFICATION',
    ATHLETE_PHOTO = 'ATHLETE_PHOTO',
    SIGNED_DCF = 'SIGNED_DCF',
    DCO_REPORT = 'DCO_REPORT',
    CHAIN_OF_CUSTODY = 'CHAIN_OF_CUSTODY',
}
