export enum ParticipantTypeCode {
    ATHLETE_REPRESENTATIVE = 'ATHLETE_REPRESENTATIVE',
    BLOOD_OFFICER = 'BLOOD_OFFICER',
    CHAPERONE = 'CHAPERONE',
    COACH = 'COACH',
    DCO = 'DCO',
    DOCTOR = 'DOCTOR',
    IF = 'IF',
    LEAD_DCO = 'LEAD_DCO',
    MAJOR_GAME_REPRESENTATIVE = 'MGREP',
    OTHER = 'OTHER',
    URINE_WITNESS = 'URINE_WITNESS',
}
