export enum SpecificCode {
    AthleteOnlyByUser = 'AthleteOnlyByUser',
    AutomaticMatchType1 = 'AutomaticMatchType1',
    AutomaticMatchType2 = 'AutomaticMatchType2',
    AutomaticMatchType3 = 'AutomaticMatchType3',
    AutomaticMatchType4 = 'AutomaticMatchType4',
    Cancel = 'Cancel',
    Closed = 'Closed',
    Complete = 'Complete',
    CompleteADRV = 'CompleteADRV',
    CompleteNoADRV = 'CompleteNoADRV',
    ConfirmedByUser = 'ConfirmedByUser',
    MatchRejectedByUser = 'MatchRejectedByUser',
    NoAutomaticMatch = 'NoAutomaticMatch',
    None = '',
    NotProcessed = 'NotProcessed',
    Pending = 'Pending',
    Planned = 'Planned',
    Rejected = 'Rejected',
}
